In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [5]:
import numpy as np

arr1= np.array([1,2,3,4,5])
arr2= np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [13]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [18]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [19]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [21]:
myarr.shape

(4, 3)

In [22]:
myarr.size

12

In [23]:
myarr.ndim

2

In [25]:
myarr.dtype

dtype('int32')

In [6]:
reshaped  = myarr.reshape((3,4))

In [3]:
import numpy as np

In [5]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [8]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [9]:
reshaped  = myarr.reshape((3,4))

In [10]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [11]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [12]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])