In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[0]

1

In [9]:
flat[3]

4

In [10]:
flat[3:6]

array([4, 5, 6])

In [14]:
#Slicing

flat[:5]

array([1, 2, 3, 4, 5])

In [16]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
b=flat[3:7]   #if we want copy then we'll use .copy() for copy mrthog to get copy

In [19]:
b

array([4, 5, 6, 7])

In [20]:
b[0] = 4444

In [21]:
b

array([4444,    5,    6,    7])

In [22]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [24]:
arr = np.array([1,54,23,53,2,3,34,5,6])

In [26]:
arr[[1,4,6]]   #fancy indexing (Select Multiple elemenets)

array([54,  2, 34])

In [28]:
arr[ arr>23 ] #Boolean Masking (Filter Data) For conditions

array([54, 53, 34])

In [29]:
#Exercise For Practise

In [42]:
#Create a 3*3 array filed with random numbers and print its shape

import numpy as np
import random

arr=np.random.rand(3,3)
print(arr)
print(arr.shape)

[[0.08987207 0.77330656 0.47793079]
 [0.18142458 0.16606681 0.29608093]
 [0.5759051  0.0244095  0.28334155]]
(3, 3)


In [2]:
#Convert an array of floats [1.1,2.2,3.3] into integers

import numpy as np

float_array = np.array([1.1,2.2,3.3],dtype=float)
int_array= float_array.astype(int)

print(int_array)

[1 2 3]


In [3]:
#Use Facncy Indexing to extract even numbers from [1,2,3,4,5,6]

import numpy as np

arr=np.array([1,2,3,4,5,6])
idx=[1,3,5]

print(arr[idx])

[2 4 6]


In [6]:
#reshape a 1D array of size 9 into 3*3 matrix

import numpy as np

arr =  np.array([1,2,3,4,5,6,7,8,9])
myarr = arr.reshape((3,3))

print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#Use Boolean masking to filter numbers greater than 50 in array

import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90,100])
mask = arr>50
print(arr[mask])

[ 60  70  80  90 100]
