In [2]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(np.sum(arr,axis=0)) #Axis=0(rows)  Sum along rows(down each column)
print(np.sum(arr,axis=1)) #Axis=1(columns)  sum along columns( across each row)

[12 15 18]
[ 6 15 24]


In [7]:
arr[0:2 , 1:3]

array([[2, 3],
       [5, 6]])

In [8]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [9]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]
